# Generated by Django 4.2.16 on 2024-10-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDetail', '0010_patientsdetail_record_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsdetail',
            old_name='left_eye_image_url',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='patientsdetail',
            old_name='left_eye_prediction',
            new_name='prediction',
        ),
        migrations.RemoveField(
            model_name='patientsdetail',
            name='right_eye_image_url',
        ),
        migrations.RemoveField(
            model_name='patientsdetail',
            name='right_eye_prediction',
        ),
    ]
